project:
  type: website
  output-dir: docs
website:
  title: "Final Project By Cy Hwang"
  navbar:
    left:
      - index.qmd
      - projects.qmd
      - explo.qmd

format:
  html:
    theme: sandstone
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#0013d5"
    linkcolor: '#ff33f0'
    monofont: courier new
    css: styles.css
    toc: true
    code-fold: true
    echo: false

editor: visual

